### ISSUE TITLE
Name clash

### ISSUE THREAD

**Issue by cies** [MichaelBurge/haskoin#1]
I raised an issue over at another Haskoin project:

https://github.com/haskoin/haskoin/issues/339

Because I was confused by this repo (I thought it was an old repo of the other project). Maybe it is good to refer to the `haskoin/haskoin` from this project's README to avoid this kind of confusion.

**Comment by MichaelBurge** [comment]
I added a note to the README linking to the other Haskoin.

**Comment by cies** [comment]
Tnx!
